/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SessionRouteImport } from './routes/session'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardUnitsRouteImport } from './routes/(dashboard)/units'
import { Route as dashboardSettingsRouteImport } from './routes/(dashboard)/settings'
import { Route as dashboardReviewRouteImport } from './routes/(dashboard)/review'
import { Route as dashboardDictionaryRouteImport } from './routes/(dashboard)/dictionary'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardUnitsRoute = dashboardUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardSettingsRoute = dashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardReviewRoute = dashboardReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardDictionaryRoute = dashboardDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => dashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/session': typeof SessionRoute
  '/study': typeof StudyRoute
  '/dictionary': typeof dashboardDictionaryRoute
  '/review': typeof dashboardReviewRoute
  '/settings': typeof dashboardSettingsRoute
  '/units': typeof dashboardUnitsRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/session': typeof SessionRoute
  '/study': typeof StudyRoute
  '/dictionary': typeof dashboardDictionaryRoute
  '/review': typeof dashboardReviewRoute
  '/settings': typeof dashboardSettingsRoute
  '/units': typeof dashboardUnitsRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/session': typeof SessionRoute
  '/study': typeof StudyRoute
  '/(dashboard)/dictionary': typeof dashboardDictionaryRoute
  '/(dashboard)/review': typeof dashboardReviewRoute
  '/(dashboard)/settings': typeof dashboardSettingsRoute
  '/(dashboard)/units': typeof dashboardUnitsRoute
  '/(dashboard)/': typeof dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/session'
    | '/study'
    | '/dictionary'
    | '/review'
    | '/settings'
    | '/units'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/session'
    | '/study'
    | '/dictionary'
    | '/review'
    | '/settings'
    | '/units'
    | '/'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/session'
    | '/study'
    | '/(dashboard)/dictionary'
    | '/(dashboard)/review'
    | '/(dashboard)/settings'
    | '/(dashboard)/units'
    | '/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  SessionRoute: typeof SessionRoute
  StudyRoute: typeof StudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/units': {
      id: '/(dashboard)/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof dashboardUnitsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/review': {
      id: '/(dashboard)/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof dashboardReviewRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/dictionary': {
      id: '/(dashboard)/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof dashboardDictionaryRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardDictionaryRoute: typeof dashboardDictionaryRoute
  dashboardReviewRoute: typeof dashboardReviewRoute
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardUnitsRoute: typeof dashboardUnitsRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardDictionaryRoute: dashboardDictionaryRoute,
  dashboardReviewRoute: dashboardReviewRoute,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardUnitsRoute: dashboardUnitsRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  SessionRoute: SessionRoute,
  StudyRoute: StudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
